version: '3'

tasks:
  build:
    desc: Build Gopher CLI
    cmds:
    - GOFLAGS=-mod=mod go build -o bin/gopher-cli main.go

  run:
    desc: Run Gopher CLI
    cmds:
    - GOFLAGS=-mod=mod go run main.go

  clean:
    desc: remove all retrieved *.png files
    cmds:
    - rm *.png
